parameters:
    phphinder.storage: 'json' # 'dbal', 'json', 'redis'
    phphinder.name: 'var'
    phphinder.auto_sync: true
services:
    PHPhinderBundle\Factory\StorageFactory:
        arguments:
            $storageType: '%phphinder.storage%'
            $name: '%phphinder.name%'

    phphinder.storage_factory:
        alias: PHPhinderBundle\Factory\StorageFactory

    PHPhinderBundle\Schema\SchemaGenerator:
        class: PHPhinderBundle\Schema\SchemaGenerator
        arguments:
            $cacheDir: '%kernel.cache_dir%/phphinder'

    phphinder.schema_generator:
        alias: PHPhinderBundle\Schema\SchemaGenerator

    PHPhinderBundle\EventListener\SchemaListener:
        arguments:
            $schemaGenerator: '@phphinder.schema_generator'
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'loadClassMetadata'

    PHPhinderBundle\EventListener\EntityListener:
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $autoSync: '%phphinder.auto_sync%'
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'postPersist'
            -
                name: 'doctrine.event_listener'
                event: 'postUpdate'
    PHPhinderBundle\EventSubscriber\SyncEventSubscriber:
        arguments:
            $schemaGenerator: '@PHPhinderBundle\Schema\SchemaGenerator'
            $factory: '@phphinder.storage_factory'
        tags:
            -
                name: 'kernel.event_listener'
                event: 'sync.event'
