services:
    PHPhinderBundle\Factory\StorageFactory:
        arguments:
            $storageType: '%phphinder.storage%'
            $name: '%phphinder.name%'
            $projectDir: '%kernel.project_dir%'

    phphinder.storage_factory:
        alias: PHPhinderBundle\Factory\StorageFactory

    PHPhinderBundle\Schema\SchemaGenerator:
        class: PHPhinderBundle\Schema\SchemaGenerator
        arguments:
            $cacheDir: '%kernel.cache_dir%/phphinder'

    phphinder.schema_generator:
        alias: PHPhinderBundle\Schema\SchemaGenerator

    PHPhinderBundle\EventListener\SchemaListener:
        arguments:
            $schemaGenerator: '@phphinder.schema_generator'
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'loadClassMetadata'

    PHPhinderBundle\EventListener\EntityListener:
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $autoSync: '%phphinder.auto_sync%'
            $syncInBackground: '%phphinder.sync_in_background%'
            $messenger: '@Symfony\Component\Messenger\MessageBusInterface'
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'postPersist'
            -
                name: 'doctrine.event_listener'
                event: 'postUpdate'
    PHPhinderBundle\EventSubscriber\SyncEventSubscriber:
        arguments:
            $schemaGenerator: '@PHPhinderBundle\Schema\SchemaGenerator'
            $factory: '@phphinder.storage_factory'
        tags:
            -
                name: 'kernel.event_listener'
                event: 'sync.event'
    PHPhinderBundle\Message\SyncMessageHandler:
        arguments:
            $objectManager: '@doctrine.orm.default_entity_manager'
            $eventDispatcher: '@event_dispatcher'
        tags:
            -
                name: 'messenger.message_handler'
                handles: 'PHPhinderBundle\Message\SyncMessage'